import test from 'node:test';
import assert from 'node:assert/strict';
import { createPresentationArtifact } from '../runtime/presentation/artifact.mjs';
import { resolvePresentationCapability } from '../runtime/presentation/registry.mjs';

test('Archify is selected for architecture maps when available', () => {
  const capability = resolvePresentationCapability({ type: 'architecture-map', availableCapabilityIds: ['archify', 'explain-him-safe-text'] });
  assert.equal(capability.id, 'archify');
  assert.equal(capability.execution, 'personal-agent');
});

test('safe text is used when specialized capability is unavailable', () => {
  const capability = resolvePresentationCapability({ type: 'architecture-map', availableCapabilityIds: ['explain-him-safe-text'] });
  assert.equal(capability.id, 'explain-him-safe-text');
  assert.equal(capability.fallback, true);
});

test('explicit consumer request wins when allowed and available', () => {
  const capability = resolvePresentationCapability({
    type: 'architecture-map', requestedCapabilityId: 'explain-him-safe-text',
    availableCapabilityIds: ['archify', 'explain-him-safe-text']
  });
  assert.equal(capability.id, 'explain-him-safe-text');
});

test('presentation artifact rejects executable HTML channels', () => {
  assert.throws(() => createPresentationArtifact({
    type: 'architecture-map',
    capability: { id: 'archify', trust: 'originator-approved', execution: 'personal-agent' },
    content: { schema: 'archify.architecture.v1', payload: { html: '<script>alert(1)</script>' } },
    fallback: { title: 'Architecture', body: 'Safe fallback' }
  }), /forbidden/);
});

test('presentation artifact preserves provenance', () => {
  const artifact = createPresentationArtifact({
    type: 'architecture-map',
    capability: { id: 'archify', trust: 'originator-approved', execution: 'personal-agent' },
    content: { schema: 'archify.architecture.v1', payload: { nodes: [{ id: 'agent' }] } },
    fallback: { title: 'Architecture', body: 'Architecture map generated by the personal agent.' },
    provenance: { repositoryRefs: [{ repository: 'o/r', path: 'README.md', ref: 'abc', status: 'current' }] }
  });
  assert.equal(artifact.provenance.repositoryRefs[0].path, 'README.md');
  assert.equal(artifact.capability.id, 'archify');
});
