import { createAddPresentationOperation, createRemovePresentationOperation, createUpdatePresentationOperation } from './workspace.mjs';

export const EXPLAIN_HIM_WEBMCP_TOOLS = Object.freeze(['get_explanation_contract', 'apply_explanation']);
export const EXPLAIN_HIM_UI_TOOLS = EXPLAIN_HIM_WEBMCP_TOOLS;
export const EXPLANATION_BLOCK_TYPES = Object.freeze(['callout', 'comparison', 'workflow', 'timeline', 'diagram']);
const REPOSITORY = 'andrew-veresov/explain-him';
const REPOSITORY_URL = `https://github.com/${REPOSITORY}`;
const SKILLS = Object.freeze([
  { id: 'explain-him', responsibility: 'grounding-and-repository-retrieval', path: 'skills/explain-him/SKILL.md', url: `${REPOSITORY_URL}/blob/main/skills/explain-him/SKILL.md` },
  { id: 'explain-him-presentation', responsibility: 'typed-page-presentation-and-guided-focus', path: 'skills/explain-him-presentation/SKILL.md', url: `${REPOSITORY_URL}/blob/main/skills/explain-him-presentation/SKILL.md` }
]);
const clone = (value) => JSON.parse(JSON.stringify(value));
function required(value, field, max = 500) { if (typeof value !== 'string' || !value.trim()) throw new TypeError(`${field} must be a non-empty string`); if (value.trim().length > max) throw new RangeError(`${field} exceeds ${max} characters`); return value.trim(); }
function optional(value, max = 500) { return value === undefined || value === null || value === '' ? null : required(value, 'optional text', max); }
function titleFor(name) { return name.split('_').map((word) => word[0].toUpperCase() + word.slice(1)).join(' '); }
function targetDescriptors(workspace) { const nodes = workspace.document?.querySelectorAll?.('[data-eh-block-id]'); if (!nodes) return (workspace.getContext?.().authoredTargetIds || []).map((id) => ({ id, title: id, replaceable: true, acceptedTypes: [...EXPLANATION_BLOCK_TYPES] })); return [...nodes].map((node) => ({ id: node.dataset.ehBlockId, title: String(node.querySelector?.('h1,h2,h3,h4,strong')?.textContent || node.dataset.ehBlockId).trim().slice(0, 120), replaceable: node.dataset.ehReplaceable !== 'false', acceptedTypes: [...EXPLANATION_BLOCK_TYPES] })); }
function localDescriptors(workspace) { return (workspace.getVisibleState?.().presentations || []).map((item) => ({ id: item.id, targetId: item.targetId, placement: item.placement, type: item.artifact?.type, title: item.artifact?.fallback?.title, updatedAt: item.updatedAt })); }
function contractFor(workspace) { const base = workspace.getContext?.() || {}; return { schemaVersion: 'explain-him-webmcp-contract.v2', explanationId: base.explanationId || null, baseRevision: base.baseRevision || null, workspaceRevision: base.workspaceRevision ?? 0, repository: { fullName: REPOSITORY, url: REPOSITORY_URL }, skills: SKILLS, skillLoadOrder: SKILLS.map((skill) => skill.id), instruction: 'Call this contract first. Load the grounding skill, ground the answer with the page and repository when necessary, then load the presentation skill before applying a visible page adaptation.', blockSchema: { path: 'schemas/explanation-block.v1.schema.json', url: `${REPOSITORY_URL}/blob/main/schemas/explanation-block.v1.schema.json`, types: [...EXPLANATION_BLOCK_TYPES] }, targets: targetDescriptors(workspace), localBlocks: localDescriptors(workspace), applyOperations: ['add', 'replace', 'update', 'remove', 'focus'], authoredLayerMutable: false, repositoryAccessViaWebMcp: false }; }
function source(value) { if (!value || typeof value !== 'object') throw new TypeError('source must be an object'); return { repository: optional(value.repository, 200) || REPOSITORY, path: required(value.path, 'sources.path', 500), ref: optional(value.ref, 160), section: optional(value.section, 300), status: optional(value.status, 40) }; }
function sources(value) { return value === undefined ? [] : Array.isArray(value) && value.length <= 20 ? value.map(source) : (() => { throw new TypeError('sources must contain 0 to 20 entries'); })(); }
function safeObject(value, field) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${field} must be an object`); for (const key of Object.keys(value)) if (['html', 'innerhtml', 'outerhtml', 'srcdoc', 'script', 'javascript', 'svg', 'selector'].includes(key.toLowerCase())) throw new TypeError(`${field}.${key} is forbidden`); return value; }
function validateBlock(input) {
  const block = safeObject(input, 'block'); const type = required(block.type, 'block.type', 40); if (!EXPLANATION_BLOCK_TYPES.includes(type)) throw new TypeError(`Unsupported explanation block type: ${type}`); const title = required(block.title, 'block.title', 160); const refs = sources(block.sources);
  if (type === 'callout') return { type, title, body: required(block.body, 'block.body', 5000), tone: ['neutral', 'example', 'warning', 'insight'].includes(block.tone) ? block.tone : 'neutral', sources: refs };
  if (type === 'comparison') { if (!Array.isArray(block.columns) || block.columns.length < 2 || block.columns.length > 4) throw new TypeError('comparison.columns must contain 2 to 4 columns'); return { type, title, sources: refs, columns: block.columns.map((column) => ({ title: required(column?.title, 'comparison.columns.title', 120), items: Array.isArray(column?.items) && column.items.length ? column.items.slice(0, 10).map((item) => required(item, 'comparison.columns.items', 500)) : (() => { throw new TypeError('comparison.columns.items must not be empty'); })() })) }; }
  if (type === 'workflow') { if (!Array.isArray(block.steps) || block.steps.length < 2 || block.steps.length > 12) throw new TypeError('workflow.steps must contain 2 to 12 steps'); return { type, title, sources: refs, steps: block.steps.map((step) => ({ title: required(step?.title, 'workflow.steps.title', 120), body: optional(step?.body, 800) })) }; }
  if (type === 'timeline') { if (!Array.isArray(block.items) || block.items.length < 2 || block.items.length > 16) throw new TypeError('timeline.items must contain 2 to 16 items'); return { type, title, sources: refs, items: block.items.map((item) => ({ label: required(item?.label, 'timeline.items.label', 100), body: required(item?.body, 'timeline.items.body', 800) })) }; }
  if (!Array.isArray(block.nodes) || block.nodes.length < 2 || block.nodes.length > 16) throw new TypeError('diagram.nodes must contain 2 to 16 nodes'); const nodes = block.nodes.map((node) => ({ id: required(node?.id, 'diagram.nodes.id', 80), label: required(node?.label, 'diagram.nodes.label', 140), body: optional(node?.body, 600) })); const ids = new Set(nodes.map((node) => node.id)); if (ids.size !== nodes.length) throw new TypeError('diagram node IDs must be unique'); const edges = block.edges === undefined ? [] : Array.isArray(block.edges) && block.edges.length <= 30 ? block.edges.map((edge) => { const from = required(edge?.from, 'diagram.edges.from', 80); const to = required(edge?.to, 'diagram.edges.to', 80); if (!ids.has(from) || !ids.has(to)) throw new TypeError('diagram edges must reference existing node IDs'); return { from, to, label: optional(edge?.label, 120) }; }) : (() => { throw new TypeError('diagram.edges must contain 0 to 30 entries'); })(); return { type, title, sources: refs, variant: ['concept', 'architecture', 'sequence', 'flow'].includes(block.variant) ? block.variant : 'concept', nodes, edges };
}
function fallbackBody(block) { if (block.type === 'callout') return block.body; if (block.type === 'comparison') return block.columns.map((column) => `${column.title}: ${column.items.join('; ')}`).join('\n'); if (block.type === 'workflow') return block.steps.map((step, index) => `${index + 1}. ${step.title}${step.body ? ` – ${step.body}` : ''}`).join('\n'); if (block.type === 'timeline') return block.items.map((item) => `${item.label}: ${item.body}`).join('\n'); return [...block.nodes.map((node) => `${node.id}: ${node.label}${node.body ? ` – ${node.body}` : ''}`), ...block.edges.map((edge) => `${edge.from} -> ${edge.to}${edge.label ? ` (${edge.label})` : ''}`)].join('\n'); }
function artifactFor(input, targetId) { const block = validateBlock(input); const { sources: repositoryRefs, ...payload } = block; return { type: block.type, capability: { id: 'explain-him-safe-block', trust: 'builtin', execution: 'embedded' }, content: { schema: `explain-him.block.${block.type}.v1`, payload }, fallback: { title: block.title, body: fallbackBody(block) }, provenance: { sourceBlockIds: [targetId], repositoryRefs }, authorship: { meaning: 'personal-agent', presentation: 'explain-him-safe-block', requestedBy: 'agent' } }; }
function prepare(workspace, input) {
  if (!input || typeof input !== 'object') throw new TypeError('input must be an object'); if (!Array.isArray(input.operations) || !input.operations.length || input.operations.length > 8) throw new TypeError('operations must contain 1 to 8 items'); const targets = new Map(targetDescriptors(workspace).map((item) => [item.id, item])); const locals = new Map(localDescriptors(workspace).map((item) => [item.id, item])); const created = new Map(); const mutations = []; const focuses = [];
  for (const raw of input.operations) { const operation = safeObject(raw, 'operation'); const op = required(operation.op, 'operation.op', 20); if (op === 'focus') { if (operation.blockId) { const blockId = required(operation.blockId, 'operation.blockId', 120); if (!locals.has(blockId) && !created.has(blockId)) throw new RangeError(`Unknown local explanation block: ${blockId}`); focuses.push({ op, blockId }); } else { const targetId = required(operation.targetId, 'operation.targetId', 120); if (!targets.has(targetId)) throw new RangeError(`Unknown authored target: ${targetId}`); focuses.push({ op, targetId }); } continue; }
    if (op === 'add' || op === 'replace') { const targetId = required(operation.targetId, 'operation.targetId', 120); const target = targets.get(targetId); if (!target) throw new RangeError(`Unknown authored target: ${targetId}`); if (op === 'replace' && !target.replaceable) throw new RangeError(`Target is not replaceable: ${targetId}`); if (op === 'replace' && [...locals.values(), ...created.values()].some((item) => item.targetId === targetId && item.placement === 'replace')) throw new RangeError(`Target already has a local replacement: ${targetId}`); const id = operation.blockId ? required(operation.blockId, 'operation.blockId', 120) : null; if (id && (!id.startsWith('local-') || locals.has(id) || created.has(id))) throw new RangeError(`Invalid new local block ID: ${id}`); const add = createAddPresentationOperation({ targetId, placement: op === 'replace' ? 'replace' : 'after', artifact: artifactFor(operation.block, targetId), actor: { kind: 'agent', channel: 'webmcp' } }, id ? { id } : {}); created.set(add.presentation.id, add.presentation); mutations.push({ op, operation: add }); continue; }
    if (op === 'update') { const blockId = required(operation.blockId, 'operation.blockId', 120); const current = locals.get(blockId) || created.get(blockId); if (!blockId.startsWith('local-') || !current) throw new RangeError(`Unknown local explanation block: ${blockId}`); const update = createUpdatePresentationOperation(blockId, { artifact: artifactFor(operation.block, current.targetId) }); mutations.push({ op, blockId, operation: update }); continue; }
    if (op === 'remove') { const blockId = required(operation.blockId, 'operation.blockId', 120); if (!blockId.startsWith('local-') || (!locals.has(blockId) && !created.has(blockId))) throw new RangeError(`Unknown local explanation block: ${blockId}`); locals.delete(blockId); created.delete(blockId); mutations.push({ op, blockId, operation: createRemovePresentationOperation(blockId) }); continue; } throw new TypeError('operation.op must be add, replace, update, remove, or focus'); }
  return { requestId: input.requestId ? required(input.requestId, 'requestId', 160) : null, expectedWorkspaceRevision: input.expectedWorkspaceRevision, mutations, focuses };
}
function stableJson(value) { if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`; return JSON.stringify(value); }
function requestFingerprint(input) { return stableJson({ operations: input?.operations || [] }); }
async function applyOperations(workspace, input) { const requestId = input?.requestId ? required(input.requestId, 'requestId', 160) : null; const fingerprint = requestFingerprint(input); const existing = requestId ? workspace.getLocalChangeHistory?.().transactions?.find((item) => item.requestId === requestId) : null; if (existing) { if (!existing.requestFingerprint || existing.requestFingerprint !== fingerprint) throw new RangeError(`requestId ${requestId} was already used with a different payload`); if (!existing.result) throw new RangeError(`requestId ${requestId} has no replayable result`); return { ...clone(existing.result), idempotent: true }; } const plan = prepare(workspace, input); const currentRevision = workspace.getContext?.().workspaceRevision ?? 0; if (plan.expectedWorkspaceRevision !== undefined && plan.expectedWorkspaceRevision !== currentRevision) throw new RangeError(`Stale workspace revision: expected ${plan.expectedWorkspaceRevision}, current ${currentRevision}`); if (plan.mutations.length) await workspace.applyTransaction(plan.mutations.map((item) => item.operation), { requestId: plan.requestId, requestFingerprint: fingerprint, actor: { kind: 'agent', channel: 'webmcp' } }); const applied = plan.mutations.map((item) => ({ op: item.op, blockId: item.operation.presentation?.id || item.blockId, targetId: item.operation.presentation?.targetId || undefined, type: item.operation.presentation?.artifact.type || undefined })); for (const focus of plan.focuses) { const value = workspace.focusBlock(focus); applied.push({ op: 'focus', ...value }); } const history = workspace.getLocalChangeHistory?.(); const result = { ok: true, idempotent: false, requestId: plan.requestId, transactionId: plan.mutations.length ? history?.transactions?.at(-1)?.id || null : null, workspaceRevision: workspace.getContext?.().workspaceRevision ?? currentRevision, applied, localBlocks: localDescriptors(workspace) }; if (result.transactionId && workspace.attachTransactionResult) await workspace.attachTransactionResult(result.transactionId, result); return result; }
function sourceSchema() { return { type: 'object', additionalProperties: false, required: ['path'], properties: { repository: { type: 'string', maxLength: 200 }, path: { type: 'string', minLength: 1, maxLength: 500 }, ref: { type: 'string', maxLength: 160 }, section: { type: 'string', maxLength: 300 }, status: { type: 'string', maxLength: 40 } } }; }
function typedBlockSchema() {
  const common = { title: { type: 'string', minLength: 1, maxLength: 160 }, sources: { type: 'array', maxItems: 20, items: sourceSchema() } };
  const variant = (type, requiredFields, properties) => ({ type: 'object', additionalProperties: false, required: ['type', 'title', ...requiredFields], properties: { type: { const: type }, ...common, ...properties } });
  const column = { type: 'object', additionalProperties: false, required: ['title', 'items'], properties: { title: { type: 'string', minLength: 1, maxLength: 120 }, items: { type: 'array', minItems: 1, maxItems: 10, items: { type: 'string', minLength: 1, maxLength: 500 } } } };
  const step = { type: 'object', additionalProperties: false, required: ['title'], properties: { title: { type: 'string', minLength: 1, maxLength: 120 }, body: { type: 'string', maxLength: 800 } } };
  const timelineItem = { type: 'object', additionalProperties: false, required: ['label', 'body'], properties: { label: { type: 'string', minLength: 1, maxLength: 100 }, body: { type: 'string', minLength: 1, maxLength: 800 } } };
  const node = { type: 'object', additionalProperties: false, required: ['id', 'label'], properties: { id: { type: 'string', minLength: 1, maxLength: 80 }, label: { type: 'string', minLength: 1, maxLength: 140 }, body: { type: 'string', maxLength: 600 } } };
  const edge = { type: 'object', additionalProperties: false, required: ['from', 'to'], properties: { from: { type: 'string', minLength: 1, maxLength: 80 }, to: { type: 'string', minLength: 1, maxLength: 80 }, label: { type: 'string', maxLength: 120 } } };
  return {
    oneOf: [
      variant('callout', ['body'], { body: { type: 'string', minLength: 1, maxLength: 5000 }, tone: { enum: ['neutral', 'example', 'warning', 'insight'] } }),
      variant('comparison', ['columns'], { columns: { type: 'array', minItems: 2, maxItems: 4, items: column } }),
      variant('workflow', ['steps'], { steps: { type: 'array', minItems: 2, maxItems: 12, items: step } }),
      variant('timeline', ['items'], { items: { type: 'array', minItems: 2, maxItems: 16, items: timelineItem } }),
      variant('diagram', ['nodes'], { variant: { enum: ['concept', 'architecture', 'sequence', 'flow'] }, nodes: { type: 'array', minItems: 2, maxItems: 16, items: node }, edges: { type: 'array', maxItems: 30, items: edge } })
    ]
  };
}
function applySchema() {
  const block = typedBlockSchema();
  const localId = { type: 'string', pattern: '^local-[A-Za-z0-9._:-]+$', maxLength: 120 };
  const targetId = { type: 'string', minLength: 1, maxLength: 120 };
  const operation = (op, requiredFields, properties) => ({ type: 'object', additionalProperties: false, required: ['op', ...requiredFields], properties: { op: { const: op }, ...properties } });
  return {
    type: 'object', required: ['operations'], additionalProperties: false,
    properties: {
      requestId: { type: 'string', minLength: 1, maxLength: 160 },
      expectedWorkspaceRevision: { type: 'integer', minimum: 0 },
      operations: {
        type: 'array', minItems: 1, maxItems: 8,
        items: {
          oneOf: [
            operation('add', ['targetId', 'block'], { targetId, blockId: localId, block }),
            operation('replace', ['targetId', 'block'], { targetId, blockId: localId, block }),
            operation('update', ['blockId', 'block'], { blockId: localId, block }),
            operation('remove', ['blockId'], { blockId: localId }),
            { type: 'object', additionalProperties: false, required: ['op'], properties: { op: { const: 'focus' }, targetId, blockId: localId }, oneOf: [{ required: ['targetId'] }, { required: ['blockId'] }] }
          ]
        }
      }
    }
  };
}
export function resolveWebMcpHost(environment = globalThis) { const standard = environment?.document?.modelContext; if (standard && typeof standard.registerTool === 'function') return { modelContext: standard, source: 'document.modelContext', standard: true }; const legacy = environment?.navigator?.modelContext; if (legacy && typeof legacy.registerTool === 'function') return { modelContext: legacy, source: 'navigator.modelContext', standard: false }; return { modelContext: null, source: 'none', standard: false }; }
export function createWebMcpTools(workspace) { let contractRead = false; return [{ name: 'get_explanation_contract', title: titleFor('get_explanation_contract'), description: 'Call first for an Explain Him page. It returns the public repository, both scoped skills in load order, semantic targets, current local presentations, and the typed contract. Skills own grounding and repository retrieval.', annotations: { readOnlyHint: true }, inputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async () => { contractRead = true; return contractFor(workspace); } }, { name: 'apply_explanation', title: titleFor('apply_explanation'), description: 'After loading both skills and grounding the answer, atomically add, replace, update, remove, or focus safe local page presentations. The canonical authored source is never written. Call get_explanation_contract first; use expectedWorkspaceRevision and requestId for safe retries.', annotations: { readOnlyHint: false }, inputSchema: applySchema(), execute: async (input) => { if (!contractRead) throw new TypeError('Call get_explanation_contract before apply_explanation in this page session'); return applyOperations(workspace, input); } }]; }
export function registerWebMcpTools(workspace, modelContext = null, options = {}) { const resolved = modelContext && typeof modelContext.registerTool === 'function' ? { modelContext, source: options.hostSource || 'explicit', standard: options.standardHost ?? options.hostSource === 'document.modelContext' } : resolveWebMcpHost(options.environment || globalThis); const status = { supported: Boolean(resolved.modelContext), ok: false, verified: false, verificationError: null, hostSource: resolved.source, standardHost: resolved.standard, expectedTools: [...EXPLAIN_HIM_WEBMCP_TOOLS], registered: [], verifiedTools: [], errors: [], ready: null }; if (!resolved.modelContext) { status.ready = Promise.resolve(status); return status; } status.ready = (async () => { for (const tool of createWebMcpTools(workspace)) try { await resolved.modelContext.registerTool(tool); status.registered.push(tool.name); } catch (error) { status.errors.push({ name: tool.name, message: String(error?.message || error) }); } status.ok = !status.errors.length && status.expectedTools.every((name) => status.registered.includes(name)); if (typeof resolved.modelContext.getTools === 'function') try { const available = await resolved.modelContext.getTools(); const names = Array.isArray(available) ? available.map((item) => typeof item === 'string' ? item : item?.name) : []; status.verifiedTools = status.expectedTools.filter((name) => names.includes(name)); status.verified = status.verifiedTools.length === status.expectedTools.length; } catch (error) { status.verificationError = String(error?.message || error); } return status; })(); return status; }
